# Generated by Django 4.2.6 on 2023-11-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.IntegerField(primary_key=7, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
            ],
        ),
    ]
